POST  http://localhost:3000/api/v1/user/register
Content-Type: application/json

{   
    "userName":"abc4",
    "password":"abc4",
    "name":"ash",
    "mail_id":"ash@ggg.com",
    "DOB":"51.45.3000"
}
###

POST http://localahost:3000/api/v1/user/login 
Content-Type: application/json

{
    "userName":"abc1",
    "password":"abc1"}
###

GET http://localhost:3000/api/v1/follow/followers

