POST  http://localhost:3000/api/v1/user/register
Content-Type: application/json

{   
    "userName":"bar14",
    "password":"bar14",
    "name":"queen",
    "mail_id":"queen@ggg.com",
    "DOB":"28.45.3000"
}
###

POST http://localahost:3000/api/v1/user/login 
Content-Type: application/json

{
    "userName":"bar12",
    "password":"bar12"
}
###
